In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Iris.csv to Iris (1).csv
Saving nba.csv to nba (2).csv

**Descriptive Statistics - Measures of Central Tendency and
variability**

Perform the following operations on any open-source dataset (e.g.,
data.csv)

1. Provide summary statistics (mean, median, minimum,
maximum, standard deviation) for a dataset (age, income etc.)
with numeric variables grouped by one of the qualitative
(categorical) variable. For example, if your categorical variable
is age groups and quantitative variable is income, then provide
summary statistics of income grouped by the age groups. Create
a list that contains a numeric value for each response to the
categorical variable.
2. Write a Python program to display some basic statistical details
like percentile, mean, standard deviation etc. of the species of
‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris- versicolor’ of iris.csv
dataset.
Provide the codes with outputs and explain everything that you do in
this step.

In [83]:
import pandas as pd
import numpy as np
import seaborn as sns

In [52]:
df=pd.read_csv("nba.csv")
iris=pd.read_csv("Iris.csv")

**1. Summary Statistics of grouped data**

In [53]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [54]:
df.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [55]:
df.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [56]:
for col in df.columns:
    if df[col].dtype=='object':
      df[col]=df[col].fillna(df[col].mode()[0])

In [57]:
df.isnull().sum()

Name         0
Team         0
Number       1
Position     0
Age          1
Height       0
Weight       1
College      0
Salary      12
dtype: int64

In [58]:
for col in df.columns:
  if df[col].dtype=="float":
    mean=df[col].mean()
    df[col]=df[col].fillna(mean)

for col in df.columns:
  if df[col].dtype=="float":
    df[col]=df[col].astype("int")

df.isnull().sum()

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

In [61]:
df["Height"]=df["Height"].astype("string")
df["Height"]=df["Height"].str.replace("-", ".", regex=False)
df["Height"]=df["Height"].astype("float")

df.dtypes

Name         object
Team         object
Number        int64
Position     object
Age           int64
Height      float64
Weight        int64
College      object
Salary        int64
dtype: object

In [62]:
df["Height"].head()

0    6.2
1    6.6
2    6.5
3    6.5
4    6.1
Name: Height, dtype: float64

In [63]:
#Mean
for col in df.columns:
  if df[col].dtype=="int" or df[col].dtype=="float":
    print(f"Mean of {col}= {df[col].mean()}")

Mean of Number= 17.676855895196507
Mean of Age= 26.936681222707424
Mean of Height= 6.517969432314411
Mean of Weight= 221.52183406113537
Mean of Salary= 4842684.102620088

In [72]:
#Median
for col in df.columns:
  if df[col].dtype=="int" or df[col].dtype=="float":
    print(f"Median of {col}= {df[col].median()}")

Median of Number= 13.0
Median of Age= 26.0
Median of Height= 6.6
Median of Weight= 220.0
Median of Salary= 2880600.0

In [73]:
#Mode
for col in df.columns:
  if df[col].dtype=="int" or df[col].dtype=="float":
    print(f"Mode of {col}= {df[col].mode()[0]}")

Mode of Number= 5
Mode of Age= 24
Mode of Height= 6.1
Mode of Weight= 220
Mode of Salary= 947276

In [74]:
#Standard Deviation
for col in df.columns:
  if df[col].dtype=="int" or df[col].dtype=="float":
    print(f"Standard Dev of {col}= {df[col].std()}")

Standard Dev of Number= 15.94864396617882
Standard Dev of Age= 4.399414063696201
Standard Dev of Height= 0.35227429750526434
Standard Dev of Weight= 26.339488773302435
Standard Dev of Salary= 5160125.694003381

In [75]:
#Variance
for col in df.columns:
  if df[col].dtype=="int" or df[col].dtype=="float":
    print(f"Variance of {col}= {df[col].var()}")

Variance of Number= 254.35924435993206
Variance of Age= 19.354844103847928
Variance of Height= 0.12409718068282748
Variance of Weight= 693.768668838925
Variance of Salary= 26626897177913.875

In [76]:
#Min
for col in df.columns:
  if df[col].dtype=="int" or df[col].dtype=="float":
    print(f"Min of {col}= {df[col].min()}")

Min of Number= 0
Min of Age= 19
Min of Height= 5.11
Min of Weight= 161
Min of Salary= 30888

In [77]:
#Max
for col in df.columns:
  if df[col].dtype=="int" or df[col].dtype=="float":
    print(f"Max of {col}= {df[col].max()}")

Max of Number= 99
Max of Age= 40
Max of Height= 7.3
Max of Weight= 307
Max of Salary= 25000000

In [78]:
#Range
for col in df.columns:
  if df[col].dtype=="int" or df[col].dtype=="float":
    print(f"Range of {col}= {df[col].max()-df[col].min()}")

Range of Number= 99
Range of Age= 21
Range of Height= 2.1899999999999995
Range of Weight= 146
Range of Salary= 24969112

In [81]:
for col in df.columns:
    if df[col].dtype in ['int','float']:
        q1=np.percentile(df[col],25)
        q2=np.percentile(df[col],50)
        q3=np.percentile(df[col],75)
        print(f" For {col}  Q1: {q1} , Q2: {q2} ,Q3: {q3}")

 For Number  Q1: 5.0 , Q2: 13.0 ,Q3: 25.0
 For Age  Q1: 24.0 , Q2: 26.0 ,Q3: 30.0
 For Height  Q1: 6.11 , Q2: 6.6 ,Q3: 6.8
 For Weight  Q1: 200.0 , Q2: 220.0 ,Q3: 240.0
 For Salary  Q1: 1100602.0 , Q2: 2880600.0 ,Q3: 6323553.0

In [88]:
bins= [19,25,31,36,40]
labels = ['19-24','25-30','31-35','36-40']
df['AgeGroup'] = pd.cut(df["Age"], bins=bins, labels=labels)

df['AgeGroup'].value_counts()

AgeGroup
19-24    197
25-30    190
31-35     56
36-40     13
Name: count, dtype: int64

In [90]:
df.groupby('AgeGroup', observed=False)["Salary"].mean()

AgeGroup
19-24    3.041840e+06
25-30    6.626023e+06
31-35    5.113016e+06
36-40    5.351744e+06
Name: Salary, dtype: float64

In [91]:
df.groupby('AgeGroup',observed=False)['Salary'].median()

AgeGroup
19-24    1662360.0
25-30    4842684.0
31-35    3646250.0
36-40    4088019.0
Name: Salary, dtype: float64

In [94]:
df.groupby('AgeGroup',observed=False)['Salary'].describe()

,count,mean,std,min,25%,50%,75%,max
AgeGroup,,,,,,,,
19-24,197.0,3.041840e+06,3.552554e+06,30888.0,947276.00,1662360.0,3533333.0,16407501.0
25-30,190.0,6.626023e+06,5.811580e+06,55722.0,1534210.50,4842684.0,10126209.0,22970500.0
31-35,56.0,5.113016e+06,5.283815e+06,200600.0,1323709.25,3646250.0,6350000.0,22875000.0
36-40,13.0,5.351744e+06,6.508388e+06,222888.0,947726.00,4088019.0,5250000.0,25000000.0

**3. Iris Python Codes**

In [98]:
print(iris.shape)

(150, 6)

In [99]:
print(iris.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [100]:
iris.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [106]:
iris.groupby('Species', observed=False)[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]].describe().transpose()

Species              Iris-setosa  Iris-versicolor  Iris-virginica
SepalLengthCm count    50.000000        50.000000       50.000000
              mean      5.006000         5.936000        6.588000
              std       0.352490         0.516171        0.635880
              min       4.300000         4.900000        4.900000
              25%       4.800000         5.600000        6.225000
              50%       5.000000         5.900000        6.500000
              75%       5.200000         6.300000        6.900000
              max       5.800000         7.000000        7.900000
SepalWidthCm  count    50.000000        50.000000       50.000000
              mean      3.418000         2.770000        2.974000
              std       0.381024         0.313798        0.322497
              min       2.300000         2.000000        2.200000
              25%       3.125000         2.525000        2.800000
              50%       3.400000         2.800000        3.000000
              75%       3.675000         3.000000        3.175000
              max       4.400000         3.400000        3.800000
PetalLengthCm count    50.000000        50.000000       50.000000
              mean      1.464000         4.260000        5.552000
              std       0.173511         0.469911        0.551895
              min       1.000000         3.000000        4.500000
              25%       1.400000         4.000000        5.100000
              50%       1.500000         4.350000        5.550000
              75%       1.575000         4.600000        5.875000
              max       1.900000         5.100000        6.900000
PetalWidthCm  count    50.000000        50.000000       50.000000
              mean      0.244000         1.326000        2.026000
              std       0.107210         0.197753        0.274650
              min       0.100000         1.000000        1.400000
              25%       0.200000         1.200000        1.800000
              50%       0.200000         1.300000        2.000000
              75%       0.300000         1.500000        2.300000
              max       0.600000         1.800000        2.500000

In [114]:
mean={}
for col in df.columns:
    if df[col].dtype in ['int','float64']:
        total=0
        count=0
        for value in df[col]:
            if pd.notna(value):
                total=total+value
                count=count+1
        mean[col]=total/count if count!=0 else None

for i,j in mean.items():
    print(i," : " ,j)

Number  :  17.676855895196507
Age  :  26.936681222707424
Height  :  6.517969432314407
Weight  :  221.52183406113537
Salary  :  4842684.102620088

In [116]:
medians={}

for col in df.columns:
    if df[col].dtype in ['int','float64']:
        values=sorted([x for x in df[col]])
        n=len(values)
        if n==0:
            medians[col]=None
        elif n%2==1:
            medians[col]=values[n//2]
        else:
            medians[col]=(values[n//2-1]+values[n//2])/2

for i,j in medians.items():
    print(i," : " ,j)

Number  :  13.0
Age  :  26.0
Height  :  6.6
Weight  :  220.0
Salary  :  2880600.0

In [118]:
modes = {}
from collections import Counter

for col in df.columns:
    values = [x for x in df[col] if pd.notna(x)]
    if values:
        most_common = Counter(values).most_common()
        max_freq = most_common[0][1]
        mode_values = [key for key, val in most_common if val == max_freq]
        modes[col] = mode_values[0] if len(mode_values) == 1 else mode_values
    else:
        modes[col] = None

for i,j in modes.items():
    print(i," : " ,j)

Name  :  Aaron Brooks
Team  :  New Orleans Pelicans
Number  :  5
Position  :  SG
Age  :  24
Height  :  6.1
Weight  :  220
College  :  Kentucky
Salary  :  947276
AgeGroup  :  19-24