In [4]:
from google.colab import files
uploaded = files.upload()

Saving nba.csv to nba.csv

**1. Importing libraries**

In [11]:
import pandas as pd

**2. Loading dataset into pandas' dataframe**

In [9]:
df=pd.read_csv('nba.csv')

**3. Descriptive Analysis**

In [13]:
#Print start 5 rows
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [16]:
#Print last 5 rows
df.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
#Print no of rows and cols
print(df.shape)

(458, 9)

In [18]:
#Print names of columns
print(df.columns)

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [19]:
#Print data types
print(df.dtypes)

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [26]:
#Descriptive statistical information of numeric data
df.describe()

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

**4. Sorting**

In [34]:
#Ascending Order
df.sort_values(by="Age", ascending=True, inplace=False)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
226,Rashad Vaughn,Milwaukee Bucks,20.0,SG,19.0,6-6,202.0,UNLV,1733040.0
122,Devin Booker,Phoenix Suns,1.0,SG,19.0,6-6,206.0,Kentucky,2127840.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
410,Karl-Anthony Towns,Minnesota Timberwolves,32.0,C,20.0,7-0,244.0,Kentucky,5703600.0
...,...,...,...,...,...,...,...,...,...
261,Vince Carter,Memphis Grizzlies,15.0,SG,39.0,6-6,220.0,North Carolina,4088019.0
304,Andre Miller,San Antonio Spurs,24.0,PG,40.0,6-3,200.0,Utah,250750.0
298,Tim Duncan,San Antonio Spurs,21.0,C,40.0,6-11,250.0,Wake Forest,5250000.0
400,Kevin Garnett,Minnesota Timberwolves,21.0,PF,40.0,6-11,240.0,NaN,8500000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
#Sort in Descending order
df.sort_values(by="Name", ascending=False, inplace=False)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,NaN,5200000.0
271,Zach Randolph,Memphis Grizzlies,50.0,PF,34.0,6-9,260.0,Michigan State,9638555.0
402,Zach LaVine,Minnesota Timberwolves,8.0,PG,21.0,6-5,189.0,UCLA,2148360.0
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,NaN
386,Wilson Chandler,Denver Nuggets,21.0,SF,29.0,6-8,225.0,DePaul,10449438.0
...,...,...,...,...,...,...,...,...,...
404,Adreian Payne,Minnesota Timberwolves,33.0,PF,25.0,6-10,237.0,Michigan State,1938840.0
328,Aaron Harrison,Charlotte Hornets,9.0,SG,21.0,6-6,210.0,Kentucky,525093.0
356,Aaron Gordon,Orlando Magic,0.0,PF,20.0,6-9,220.0,Arizona,4171680.0
152,Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**4. Selecting cols**

In [37]:
#Seelecting single row
print(df["Name"])

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: object

In [38]:
#Selecting multiple rows
print(df[["Name", "Age", "Salary"]])

              Name   Age     Salary
0    Avery Bradley  25.0  7730337.0
1      Jae Crowder  25.0  6796117.0
2     John Holland  27.0        NaN
3      R.J. Hunter  22.0  1148640.0
4    Jonas Jerebko  29.0  5000000.0
..             ...   ...        ...
453   Shelvin Mack  26.0  2433333.0
454      Raul Neto  24.0   900000.0
455   Tibor Pleiss  26.0  2900000.0
456    Jeff Withey  26.0   947276.0
457            NaN   NaN        NaN

[458 rows x 3 columns]

In [42]:
#Selcting row using index
print(df.loc[3])

Name           R.J. Hunter
Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: 3, dtype: object

In [43]:
#Selecting between columns using index
print(df.iloc[:,1:3])

               Team  Number
0    Boston Celtics     0.0
1    Boston Celtics    99.0
2    Boston Celtics    30.0
3    Boston Celtics    28.0
4    Boston Celtics     8.0
..              ...     ...
453       Utah Jazz     8.0
454       Utah Jazz    25.0
455       Utah Jazz    21.0
456       Utah Jazz    24.0
457             NaN     NaN

[458 rows x 2 columns]

In [46]:
#Selecting using labels

#All cols between Age and Salary
print(df.loc[:, 'Age':'Salary'])

      Age Height  Weight            College     Salary
0    25.0    6-2   180.0              Texas  7730337.0
1    25.0    6-6   235.0          Marquette  6796117.0
2    27.0    6-5   205.0  Boston University        NaN
3    22.0    6-5   185.0      Georgia State  1148640.0
4    29.0   6-10   231.0                NaN  5000000.0
..    ...    ...     ...                ...        ...
453  26.0    6-3   203.0             Butler  2433333.0
454  24.0    6-1   179.0                NaN   900000.0
455  26.0    7-3   256.0                NaN  2900000.0
456  26.0    7-0   231.0             Kansas   947276.0
457   NaN    NaN     NaN                NaN        NaN

[458 rows x 5 columns]

In [48]:
# Print rows 13 to 14 (indices 12 to 13) and columns 4 to 7 (indices 3 to 6)
print(df.iloc[12:14, 3:7])

   Position   Age Height  Weight
12       SG  27.0    6-7   220.0
13       SG  20.0    6-6   215.0

**5. Filtering Data**

In [54]:
filtered_data=df[df["Age"]<30]
print(filtered_data.shape[0])
print(filtered_data['Age'])

335
0      25.0
1      25.0
2      27.0
3      22.0
4      29.0
       ...
452    20.0
453    26.0
454    24.0
455    26.0
456    26.0
Name: Age, Length: 335, dtype: float64

In [57]:
#Print only those rows whose college name is 'Ohio State'

filtered_data = df[df['College'] == 'Ohio State']

# Print the filtered rows
print(filtered_data['College'])
print("Number of Rows with Ohio State",filtered_data['College'].shape[0])

10     Ohio State
12     Ohio State
116    Ohio State
147    Ohio State
262    Ohio State
Name: College, dtype: object
Number of Rows with Ohio State 5

**6. Handling Missing Values**

In [60]:
#No. of Null Values for Each Col
df.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [68]:
#Replacing Numeric nulls with mean:
for col in df.columns:
  if(df[col].dtype=="float64"):
    col_mean=df[col].mean()
    df[col]=df[col].fillna(col_mean)

df.isnull().sum()

Name         1
Team         1
Number       0
Position     1
Age          0
Height       1
Weight       0
College     85
Salary       0
dtype: int64

In [103]:
#Replacing categorical with string

for col in df.columns:
  if(df[col].dtype=="object"):
    col_mode=df[col].mode()[0]
    df[col]=df[col].fillna(col_mode)

df.isnull().sum()

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

**7. Type Conversion**

In [104]:
#Converting object to string
for col in df.columns:
  if df[col].dtype=="object":
    df[col]=df[col].astype("string")

df.dtypes

Name        string[python]
Team        string[python]
Number               int64
Position    string[python]
Age                  int64
Height             float64
Weight               int64
College     string[python]
Salary      string[python]
dtype: object

In [113]:
#Replacing string with float format

df["Height"]=df["Height"].astype('string')
df["Height"]=df["Height"].str.replace("-",".",regex=False)

df["Height"]=df["Height"].astype("float")
df["Height"]

Name        string[python]
Team        string[python]
Number               int64
Position    string[python]
Age                  int64
Height             float64
Weight               int64
College     string[python]
Salary      string[python]
dtype: object

In [114]:
df['Salary']=df['Salary'].astype("float")
df['Salary']=df['Salary'].astype("int")

df.dtypes

Name        string[python]
Team        string[python]
Number               int64
Position    string[python]
Age                  int64
Height             float64
Weight               int64
College     string[python]
Salary               int64
dtype: object

**8. Label Encoding**

In [117]:
from sklearn.preprocessing import LabelEncoder

In [124]:
le=LabelEncoder()
df["Position"]=le.fit_transform(df["Position"])

df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,17,2,26,6.0,221,Texas,4842684
1,Jae Crowder,Boston Celtics,17,3,26,6.0,221,Marquette,4842684
2,John Holland,Boston Celtics,17,4,26,6.0,221,Boston University,4842684
3,R.J. Hunter,Boston Celtics,17,4,26,6.0,221,Georgia State,4842684
4,Jonas Jerebko,Boston Celtics,17,1,26,6.0,221,Kentucky,4842684

**9. Hot One Encoding**

In [127]:
df_enc=pd.get_dummies(df,columns=['Team','College'])
df_enc.head()

,Name,Number,Position,Age,Height,Weight,Salary,Team_Atlanta Hawks,Team_Boston Celtics,Team_Brooklyn Nets,...,College_Washington State,College_Weber State,College_Westchester CC,College_Western Carolina,College_Western Kentucky,College_Western Michigan,College_Wichita State,College_Wisconsin,College_Wyoming,College_Xavier
0,Avery Bradley,17,2,26,6.0,221,4842684,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1,Jae Crowder,17,3,26,6.0,221,4842684,False,True,False,...,False,False,False,False,False,False,False,False,False,False
2,John Holland,17,4,26,6.0,221,4842684,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,R.J. Hunter,17,4,26,6.0,221,4842684,False,True,False,...,False,False,False,False,False,False,False,False,False,False
4,Jonas Jerebko,17,1,26,6.0,221,4842684,False,True,False,...,False,False,False,False,False,False,False,False,False,False